const Permissions = Object.freeze({
    USER_CREATE: "USER_CREATE",
    USER_READ: "USER_READ",
    USER_UPDATE: "USER_UPDATE",
    USER_DELETE: "USER_DELETE",

    INVENTORY_CREATE: "INVENTORY_CREATE",
    INVENTORY_UPDATE: "INVENTORY_UPDATE",
    INVENTORY_DELETE: "INVENTORY_DELETE",

    APPOINTMENT_CREATE: "APPOINTMENT_CREATE",
    APPOINTMENT_UPDATE: "APPOINTMENT_UPDATE",

    EMERGENCY_CREATE: "EMERGENCY_CREATE",
    EMERGENCY_UPDATE: "EMERGENCY_UPDATE",

    ADMIN_ACCESS: "ADMIN_ACCESS",
});

export default Permissions;